# .gitlab-ci.yml
stages:
  - test

test:
  stage: test
  image: node:latest
  script:
    - npm install
    - npm run test -- --coverage
  artifacts:
    paths:
      - coverage/
    reports:
      junit: coverage/junit.xml
    coverage_report:
      coverage_format: cobertura
      path: coverage/cobertura-coverage.xml
